#!/bin/bash

CORE_PATH="/isilon/sequencing/Seq_Proj/"

PROJECT=$1

TIMESTAMP=`date '+%F.%H-%M-%S'`

cat $CORE_PATH/$PROJECT/REPORTS/OXIDATION/*txt \
| egrep -v "^#|^$|^SAMPLE" \
| awk 'BEGIN {print "SM_TAG","LIBRARY","CONTEXT","TOTAL_SITES","TOTAL_BASES","REF_NONOXO_BASES","REF_OXO_BASES","REF_TOTAL_BASES","ALT_NONOXO_BASES","ALT_OXO_BASES",\
"OXIDATION_ERROR_RATE","OXIDATION_Q","C_REF_REF_BASES","G_REF_REF_BASES","C_REF_ALT_BASES","G_REF_ALT_BASES","C_REF_OXO_ERROR_RATE","C_REF_OXO_Q","G_REF_OXO_ERROR_RATE","G_REF_OXO_Q"} \
{print $0}' \
| sed -r 's/[[:space:]]+/,/g' \
>| $CORE_PATH/$PROJECT/REPORTS/QC_REPORTS/$PROJECT".OXIDATION."$TIMESTAMP".csv"

echo
echo $PROJECT".OXIDATION."$TIMESTAMP".csv"
echo has been written to
echo $CORE_PATH/$PROJECT/REPORTS/QC_REPORTS/
